version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@iden3*"
      - dependency-name: "@0xpolygonid*"
    reviewers:
      - "Kolezhniuk"
      - "vmidyllic"
      - "volodymyr-basiuk"
